<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="GestionnaireActivites" nsURI="platform:/resource/fr/houssam/grimm/modeling"
    nsPrefix="fr.houssam.grimm.modeling">
  <eClassifiers xsi:type="ecore:EClass" name="Process">
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" lowerBound="1" eType="#//End"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//Start"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activities" eType="#//Activity"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentActivity" eType="#//Activity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PseudoState">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" eType="#//Activity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="End" eSuperTypes="#//PseudoState"/>
  <eClassifiers xsi:type="ecore:EClass" name="Start" eSuperTypes="#//PseudoState"/>
  <eClassifiers xsi:type="ecore:EClass" name="Activity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="next" eType="#//Activity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="previous" eType="#//Activity"/>
  </eClassifiers>
</ecore:EPackage>
